In [211]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

In [212]:
df = pd.read_csv("gender_submission.csv")
df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

df = pd.read_csv("titanic.csv")
df.head()

In [213]:
df.info

<bound method DataFrame.info of      PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]>

In [214]:
df.isnull().sum()

PassengerId    0
Survived       0
dtype: int64

df.plot(kind='bar', subplots=True, layout=(20,15))
plt.show()

# Decision Tree Classifier

In [215]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [216]:
x=df.drop(columns='Survived')
x.shape

(418, 1)

In [217]:
y=df['Survived']
y.shape

(418,)

In [218]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.5,random_state=2)

In [219]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [220]:
pred = model.predict(x_test)
pred

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int64)

In [221]:
model = DecisionTreeClassifier()
model.fit(x_train, y_train)
pred1 = model.predict(x_test)
score1 = accuracy_score(y_test, pred1)
print("Decision Tree Classifier Score:", score1)
print(classification_report(y_test, pred1))

Decision Tree Classifier Score: 0.5215311004784688
              precision    recall  f1-score   support

           0       0.62      0.60      0.61       131
           1       0.37      0.38      0.37        78

    accuracy                           0.52       209
   macro avg       0.49      0.49      0.49       209
weighted avg       0.53      0.52      0.52       209



# Random Forest Classifier

In [222]:
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier(n_estimators=6)

In [223]:
model2.fit(x_train,y_train)

RandomForestClassifier(n_estimators=6)

In [224]:
pred2 = model2.predict(x_test)
pred2

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [225]:
model2.score(x_test,y_test)

0.5119617224880383

In [226]:
model2.predict([[414]])

C:\Users\nages\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

# Random Forest Classifier 2

In [227]:
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10]
}
model2 = RandomForestClassifier(random_state=2)
grid_search = GridSearchCV(model2, param_grid, cv=5, scoring='accuracy')
grid_search.fit(x_train, y_train)
best_model = grid_search.best_estimator_
pred2 = best_model.predict(x_test)
score2 = accuracy_score(y_test, pred2)
print("Random Forest Classifier Score:", score2)
print(classification_report(y_test, pred2))

Random Forest Classifier Score: 0.5406698564593302
              precision    recall  f1-score   support

           0       0.61      0.74      0.67       131
           1       0.32      0.21      0.25        78

    accuracy                           0.54       209
   macro avg       0.47      0.47      0.46       209
weighted avg       0.50      0.54      0.51       209

Not Survived


C:\Users\nages\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [236]:
# Make Predictions
prediction = best_model.predict([[1]])
if prediction[0] == 0:
    print("Not Survived")
else:
    print("Survived")

Not Survived


C:\Users\nages\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


# Support Vector Machine

In [238]:
model = SVC(kernel='linear', C=12)
model.fit(x_train, y_train)
pred = model.predict(x_test)
score = accuracy_score(y_test, pred)
print("SVM Score:", score)
print(classification_report(y_test, pred))

SVM Score: 0.6267942583732058
              precision    recall  f1-score   support

           0       0.63      1.00      0.77       131
           1       0.00      0.00      0.00        78

    accuracy                           0.63       209
   macro avg       0.31      0.50      0.39       209
weighted avg       0.39      0.63      0.48       209



C:\Users\nages\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nages\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nages\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [234]:
# Make Predictions
prediction = model.predict([[62]])
if prediction[0] == 0:
    print("Not Survived")
else:
    print("Survived")

Not Survived


C:\Users\nages\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
